import fs from "fs";
import path from "path";
import chalk from "chalk";

const generateReadme = (metadata, includeBadges) => {
  if (!metadata) {
    console.log(chalk.red("Error: No project metadata found. README generation aborted."));
    return;
  }

  // Extract GitHub repo details for badges
  let repoBadgePath = "";
  if (metadata.repository && metadata.repository.includes("github.com")) {
    const repoParts = metadata.repository.split("github.com/")[1].split("/");
    const username = repoParts[0];
    const repoName = repoParts[1];

    repoBadgePath = `${username}/${repoName}`;
  }

  // Generate the README content
  let readmeContent = `# ${metadata.name}

${metadata.description}

`;

  // Add badges if the --badges flag is passed
  if (includeBadges) {
    readmeContent += `## 🏆 Badges
![GitHub stars](https://img.shields.io/github/stars/${repoBadgePath}.svg)
![GitHub issues](https://img.shields.io/github/issues/${repoBadgePath}.svg)
![GitHub license](https://img.shields.io/github/license/${repoBadgePath}.svg)
![npm downloads](https://img.shields.io/npm/dt/${metadata.name}.svg)\n\n`;
  }

  readmeContent += `## 📦 Project Details
- **Version**: ${metadata.version}
- **License**: ${metadata.license}
- **Entry File**: ${metadata.main}
- **Dependencies**: ${metadata.dependencies}

## 🚀 Getting Started
To install dependencies, run:
\`\`\`sh
npm install
\`\`\`

To start the project:
\`\`\`sh
node ${metadata.main}
\`\`\`

## 🌍 Repository
- **GitHub Repo**: ${metadata.repository}

## 📝 License
This project is licensed under the ${metadata.license} License.

---
Generated by [AutoReadMe](https://github.com/your-repo-link)
`;

  const readmePath = path.resolve(process.cwd(), "README.md");
  
  fs.writeFileSync(readmePath, readmeContent, "utf-8");
  
  console.log(chalk.green(`✅ README.md successfully created at ${readmePath}`));
};

export default generateReadme;
