import fs from "fs";
import path from "path";
import chalk from "chalk";

const generateReadme = (metadata, includeBadges) => {
  if (!metadata) {
    console.log(chalk.red("Error: No project metadata found. README generation aborted."));
    return;
  }

  // Extract GitHub repo details for badges
  let repoBadgePath = "";
  if (metadata.repository && metadata.repository.includes("github.com")) {
    const repoParts = metadata.repository.split("github.com/")[1].split("/");
    const username = repoParts[0];
    const repoName = repoParts[1];

    repoBadgePath = `${username}/${repoName}`;
  }

  let readmeContent = `# ${metadata.name} 🚀  

> ${metadata.description}  

## 📌 Table of Contents
- [🏆 Badges](#-badges)
- [📖 Overview](#-overview)
- [⚙️ Installation](#-installation)
- [🚀 Features](#-features)
- [📂 Project Structure](#-project-structure)
- [💡 Usage](#-usage)
- [👥 Contributing](#-contributing)
- [🛠️ Tech Stack](#-tech-stack)
- [📜 License](#-license)
- [🔮 Future Improvements](#-future-improvements)
- [❓ FAQ](#-faq)

`;

  if (includeBadges) {
    readmeContent += `## 🏆 Badges
![GitHub stars](https://img.shields.io/github/stars/${repoBadgePath}.svg)
![GitHub issues](https://img.shields.io/github/issues/${repoBadgePath}.svg)
![GitHub license](https://img.shields.io/github/license/${repoBadgePath}.svg)
![npm downloads](https://img.shields.io/npm/dt/${metadata.name}.svg)

`;
  }

  readmeContent += `## 📖 Overview
${metadata.description}

This project is designed to **solve XYZ problem** using **XYZ technology**. It is lightweight, highly customizable, and easy to set up.

## ⚙️ Installation

\`\`\`sh
# Clone the repository
git clone ${metadata.repository || "<repository_url>"} my-project

# Navigate to the project directory
cd my-project

# Install dependencies
npm install

# Run the application
npm start
\`\`\`

> 📝 **Note:** Make sure you have **Node.js v14+** installed before running this project.

---

## 🚀 Features
✅ Feature 1 - Description  
✅ Feature 2 - Description  
✅ Feature 3 - Description  
✅ Feature 4 - Description  

---

## 📂 Project Structure

\`\`\`sh
my-project/
│── src/               # Source code
│   ├── components/    # UI Components
│   ├── utils/         # Utility functions
│   ├── api/           # API calls
│── public/            # Static assets
│── package.json       # Project metadata
│── README.md          # Documentation
\`\`\`

> 💡 **Tip:** This is a suggested structure. You can modify it based on your needs.

---

## 💡 Usage

\`\`\`sh
# Run in development mode
npm run dev

# Build for production
npm run build

# Run tests
npm test
\`\`\`

> 🛠️ **For CLI-based projects**, replace this with example command usages.

---

## 👥 Contributing

Contributions are always welcome! To contribute:
1. **Fork the repository**
2. **Create a new branch** for your feature:
   \`\`\`sh
   git checkout -b feature-name
   \`\`\`
3. **Make your changes & commit**:
   \`\`\`sh
   git commit -m "Add feature-name"
   \`\`\`
4. **Push to your fork & submit a PR**.

---

## 🛠️ Tech Stack

🔹 **Frontend:** React, Vue, or your choice  
🔹 **Backend:** Node.js, Express  
🔹 **Database:** MongoDB, PostgreSQL  
🔹 **DevOps:** Docker, CI/CD  

---

## 📜 License
This project is licensed under the **${metadata.license}** License.

---

## 🔮 Future Improvements
- [ ] Feature 1  
- [ ] Feature 2  
- [ ] Improve performance  
- [ ] More integrations  

---

## ❓ FAQ

**Q: How do I customize this project?**  
A: Edit \`config.js\` or modify \`package.json\` settings.

**Q: Can I use this in production?**  
A: Absolutely! Follow best practices and security guidelines.

---

> 📝 **Notes:**  
> - This README file can be further **customized for different templates** like CLI tools, API projects, or open-source frameworks.  
> - The "TODO" section should be updated as features get implemented.  
> - Contributors should ensure **code consistency** with linting tools.

---

🚀 **Generated by [AutoReadMe](https://github.com/CodeTirtho97/AutoREADME)**
`;

  const readmePath = path.resolve(process.cwd(), "README.md");
  
  fs.writeFileSync(readmePath, readmeContent, "utf-8");
  
  console.log(chalk.green(`✅ README.md successfully created at ${readmePath}`));
};

export default generateReadme;
